// <auto-generated />
using System;
using Justice.Dash.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Justice.Dash.Server.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20240911093456_AddSurveillanceDayOverrides")]
    partial class AddSurveillanceDayOverrides
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: The actual BuildTargetModel content will be generated by EF Core when the migration is applied
            // This is just a placeholder for the Designer.cs file
#pragma warning restore 612, 618
        }
    }
}